apiVersion: apps/v1
kind: Deployment
metadata:
  name: familyapply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: familyapply
  template:
    metadata:
      labels:
        app: familyapply
    spec:
      containers:
      - image: okteto.dev/familyapply:latest
        name: familyapply
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0a49a311-e943-405f-93b3-4b86b76042c9"
        - name: Vless_Path
          value: "/vlessray5"
        - name: Vmess_UUID
          value: "0a49a311-e943-405f-93b3-4b86b76042c9"
        - name: Vmess_Path
          value: "/vmessray5"
        - name: Share_Path
          value: "/v2link"
